export default function handler(req, res) {
  res.status(200).json([
  		{
        'name':'Beast_Master_Fire',
  			'tc_name':'炎龍王',
        'jp_name':'炎鳳竜王・レプティアス',
        'img':'https://i.imgur.com/6bBsDRn.jpg',
  			'type':'獸王'
  		},
  		{
  			'name':'Beast_Master_Water',
        'tc_name':'冰狼王',
        'jp_name':'氷魔狼王・ヴォルハス',
        'img':'https://i.imgur.com/mkx0gPT.jpg',
        'type':'獸王'
  		},
  		{
  			'name':'Beast_Master_Wood',
        'tc_name':'嵐角王',
        'jp_name':'嵐槍角王・ドゥームエルシュ',
        'img':'https://imgur.com/zhiwE2w.jpg',
        'type':'獸王'
  		},
      {
        'name':'Beast_Master_Light',
        'tc_name':'煌寶王',
        'jp_name':'煌天宝王・フェルルナーシュ',
        'img':'https://imgur.com/2qso3dt.jpg',
        'type':'獸王'
      },
      {
        'name':'Beast_Master_Dark',
        'tc_name':'黑雷王',
        'jp_name':'黒撃雷王・ロンドハーケン',
        'img':'https://i.imgur.com/51pfFrZ.jpg',
        'type':'獸王'
      },
      {
        'name':'Beast_Emperor_Fire',
        'tc_name':'煉擊帝',
        'jp_name':'煉獄帝獣・アドラグレンド',
        'img':'https://imgur.com/ZuNNGzd.jpg',
        'type':'獸帝'
      },
      {
        'name':'Beast_Emperor_Water',
        'tc_name':'深翔帝',
        'jp_name':'深渦帝獣・エイルヴュラー',
        'img':'https://imgur.com/agpcnJK.jpg',
        'type':'獸帝'
      },
      {
        'name':'Beast_Emperor_Wood',
        'tc_name':'鏡鱗帝',
        'jp_name':'鏡蓬帝獣・ベルセデリオ',
        'img':'https://imgur.com/qF0EI3a.jpg',
        'type':'獸帝'
      },
      {
        'name':'Beast_Emperor_Light',
        'tc_name':'機皇帝',
        'jp_name':'機艦帝獣・ゾンバルディエ',
        'img':'https://imgur.com/GdBneVF.jpg',
        'type':'獸帝'
      },
      {
        'name':'Beast_Emperor_Dark',
        'tc_name':'崩滅帝',
        'jp_name':'崩律帝獣・フィアドラーク',
        'img':'https://imgur.com/sJrL10B.jpg',
        'type':'獸帝'
      },
      {
        'name':'Armed_Girl_Fire',
        'tc_name':'火裝姬',
        'jp_name':'聖遺解放フラマ',
        'img':'https://imgur.com/1aLy246.jpg',
        'type':'裝姬'
      },
      {
        'name':'Armed_Girl_Water',
        'tc_name':'水裝姬',
        'jp_name':'聖遺解放オラージュ',
        'img':'https://imgur.com/vRW5g9H.jpg',
        'type':'裝姬'
      },
      {
        'name':'Armed_Girl_Wood',
        'tc_name':'木裝姬',
        'jp_name':'聖遺解放シエル',
        'img':'https://imgur.com/1uOHaTv.jpg',
        'type':'裝姬'
      },
      {
        'name':'Armed_Girl_Light',
        'tc_name':'光裝姬',
        'jp_name':'聖遺解放エクレール',
        'img':'https://imgur.com/ytIMQ1O.jpg',
        'type':'裝姬'
      },
      {
        'name':'Armed_Girl_Dark',
        'tc_name':'暗裝姬',
        'jp_name':'聖遺解放フォンセ',
        'img':'https://imgur.com/NJOFmRA.jpg',
        'type':'裝姬'
      },
      {
        'name':'Ancient_Dragon_Fire',
        'tc_name':'火古龍',
        'jp_name':'真焔古龍・フレイバルカン',
        'img':'https://imgur.com/1dbPIt3.jpg',
        'type':'古龍'
      },
      {
        'name':'Ancient_Dragon_Water',
        'tc_name':'水古龍',
        'jp_name':'真凍古龍・エスベル',
        'img':'https://imgur.com/CqiklCo.jpg',
        'type':'古龍'
      },
      {
        'name':'Ancient_Dragon_Wood',
        'tc_name':'木古龍',
        'jp_name':'真疾古龍・ウィンフィールド',
        'img':'https://imgur.com/raYD0aH.jpg',
        'type':'古龍'
      },
      {
        'name':'Ancient_Dragon_Light',
        'tc_name':'光古龍',
        'jp_name':'真煌古龍・パルマスホーリー',
        'img':'https://imgur.com/MLdMLlT.jpg',
        'type':'古龍'
      },
      {
        'name':'Ancient_Dragon_Dark',
        'tc_name':'暗古龍',
        'jp_name':'真影古龍・ダークネイヴァー',
        'img':'https://imgur.com/u0RtrD9.jpg',
        'type':'古龍'
      },
      {
        'name':'Creation_God_Fire',
        'tc_name':'火創神',
        'jp_name':'狂創神イヴェルガンド',
        'img':'https://i.imgur.com/72MygNc.jpg',
        'type':'三創神'
      },
      {
        'name':'Creation_God_Water',
        'tc_name':'水創神',
        'jp_name':'星創神イフ',
        'img':'https://i.imgur.com/YNDwqUU.jpg',
        'type':'三創神'
      },
      {
        'name':'Creation_God_Wood',
        'tc_name':'木創神',
        'jp_name':'魔創神ロード・メイガス',
        'img':'https://i.imgur.com/8vrrpVq.jpg',
        'type':'三創神'
      },
      {
        'name':'Beast_Controller_Fire',
        'tc_name':'火獸操',
        'jp_name':'炎獣操士ネス',
        'img':'https://i.imgur.com/y82EZxH.jpg',
        'type':'獸操士'
      },
      {
        'name':'Beast_Controller_Water',
        'tc_name':'水獸操',
        'jp_name':'氷獣操士ザルバ',
        'img':'https://i.imgur.com/xsvUXtf.jpg',
        'type':'獸操士'
      },
      {
        'name':'Beast_Controller_Wood',
        'tc_name':'木獸操',
        'jp_name':'嵐獣操士ラナ',
        'img':'https://i.imgur.com/lageRfA.jpg',
        'type':'獸操士'
      },
      {
        'name':'Beast_Controller_Light',
        'tc_name':'光獸操',
        'jp_name':'光獣操士セリエ',
        'img':'https://i.imgur.com/bUIYQbR.jpg',
        'type':'獸操士'
      },
      {
        'name':'Beast_Controller_Dark',
        'tc_name':'暗獸操',
        'jp_name':'闇獣操士カティ',
        'img':'https://i.imgur.com/nNkG6WW.jpg',
        'type':'獸操士'
      },
      {
        'name':'Mechanical_Girl_Fire',
        'tc_name':'火機娘',
        'jp_name':'02式戦克:メイシン',
        'img':'https://i.imgur.com/fLAGnqg.jpg',
        'type':'機娘'
      },
      {
        'name':'Mechanical_Girl_Water',
        'tc_name':'水機娘',
        'jp_name':'61式戦克乙:シャオシン',
        'img':'https://i.imgur.com/uu5eAqC.jpg',
        'type':'機娘'
      },
      {
        'name':'Mechanical_Girl_Wood',
        'tc_name':'木機娘',
        'jp_name':'SO135:V2-アレスタ',
        'img':'https://i.imgur.com/et4AoMR.jpg',
        'type':'機娘'
      },
      {
        'name':'Mechanical_Girl_Light',
        'tc_name':'光機娘',
        'jp_name':'SO928:V2-サイリスタ',
        'img':'https://i.imgur.com/ltM0rF3.jpg',
        'type':'機娘'
      },
      {
        'name':'Mechanical_Girl_Dark',
        'tc_name':'暗機娘',
        'jp_name':'SO629c(バリスタ)',
        'img':'https://i.imgur.com/DDSr8ZT.jpg',
        'type':'機娘'
      },
      {
        'name':'Seal_Dragon_Fire',
        'tc_name':'火封龍',
        'jp_name':'暴焔竜神獣ラルグ',
        'img':'https://imgur.com/HOqlz4d.jpg',
        'type':'封龍士'
      },
      {
        'name':'Seal_Dragon_Water',
        'tc_name':'水封龍',
        'jp_name':'絶凍竜神獣シュスト',
        'img':'https://imgur.com/GMtJeN2.jpg',
        'type':'封龍士'
      },
      {
        'name':'Seal_Dragon_Wood',
        'tc_name':'木封龍',
        'jp_name':'深碧竜神獣フリネーダ',
        'img':'https://imgur.com/JyqEVAC.jpg',
        'type':'封龍士'
      },
      {
        'name':'Seal_Dragon_Light',
        'tc_name':'光封龍',
        'jp_name':'閃雷竜神獣ミレシア',
        'img':'https://imgur.com/R7ZKJU8.jpg',
        'type':'封龍士'
      },
      {
        'name':'Seal_Dragon_Dark',
        'tc_name':'暗封龍',
        'jp_name':'冥夜竜神獣クロユリ',
        'img':'https://imgur.com/9vFxtHr.jpg',
        'type':'封龍士'
      },
      {
        'name':'Sky_Astral_Fire',
        'tc_name':'火天星',
        'jp_name':'煉天星神獣マルティウス',
        'img':'https://imgur.com/4umTDZ6.jpg',
        'type':'天星'
      },
      {
        'name':'Sky_Astral_Water',
        'tc_name':'水天星',
        'jp_name':'蒼天星神獣メルクーア',
        'img':'https://imgur.com/kKugnEa.jpg',
        'type':'天星'
      },
      {
        'name':'Sky_Astral_Wood',
        'tc_name':'木天星',
        'jp_name':'獅天星神獣ジョーヴェ',
        'img':'https://imgur.com/k3lHqUh.jpg',
        'type':'天星'
      },
      {
        'name':'Sky_Astral_Light',
        'tc_name':'光天星',
        'jp_name':'虹天星神獣ヴィニエーラ',
        'img':'https://imgur.com/FqhOHIl.jpg',
        'type':'天星'
      },
      {
        'name':'Sky_Astral_Dark',
        'tc_name':'暗天星',
        'jp_name':'無天星神獣サトゥルヌス',
        'img':'https://imgur.com/P58hf3e.jpg',
        'type':'天星'
      },
      {
        'name':'Maki_Fire',
        'tc_name':'火真姬',
        'jp_name':'聖遺解放ナティエ',
        'img':'https://i.imgur.com/zbxGgTn.jpg',
        'type':'真姬'
      },
      {
        'name':'Maki_Water',
        'tc_name':'水真姬',
        'jp_name':'聖遺解放セレッサ',
        'img':'https://i.imgur.com/oiomKai.jpg',
        'type':'真姬'
      },
      {
        'name':'Maki_Wood',
        'tc_name':'木真姬',
        'jp_name':'聖遺解放シア',
        'img':'https://i.imgur.com/f1vg3XA.jpg',
        'type':'真姬'
      },
      {
        'name':'Maki_Light',
        'tc_name':'光真姬',
        'jp_name':'聖遺解放アルシェ',
        'img':'https://i.imgur.com/CITz0r9.jpg',
        'type':'真姬'
      },
      {
        'name':'Maki_Dark',
        'tc_name':'暗真姬',
        'jp_name':'聖遺解放ノア',
        'img':'https://i.imgur.com/oh1cyW4.jpg',
        'type':'真姬'
      },
      {
        'name':'Elf_King_Fire',
        'tc_name':'火精靈王',
        'jp_name':'炎精霊王グローセ',
        'img':'https://i.imgur.com/7n2yIIT.jpg',
        'type':'精靈王'
      },
      {
        'name':'Elf_King_Water',
        'tc_name':'水精靈王',
        'jp_name':'水精霊王ゼイリオン',
        'img':'https://i.imgur.com/qCgukee.jpg',
        'type':'精靈王'
      },
      {
        'name':'Elf_King_Wood',
        'tc_name':'木精靈王',
        'jp_name':'木精霊王エダード',
        'img':'https://i.imgur.com/nSP9lyh.jpg',
        'type':'精靈王'
      },
      {
        'name':'Elf_King_Light',
        'tc_name':'光精靈王',
        'jp_name':'光精霊王ユーダス',
        'img':'https://i.imgur.com/4aRVn17.jpg',
        'type':'精靈王'
      },
      {
        'name':'Elf_King_Dark',
        'tc_name':'暗精靈王',
        'jp_name':'闇精霊王ガイエス',
        'img':'https://i.imgur.com/EOp12nz.jpg',
        'type':'精靈王'
      },
      {
        'name':'Star_Beast_Girl_Fire',
        'tc_name':'火星獸姬',
        'jp_name':'律星獣姫ティセラ',
        'img':'https://i.imgur.com/jKcuuY9.jpg',
        'type':'星獸姬'
      },
      {
        'name':'Star_Beast_Girl_Water',
        'tc_name':'水星獸姬',
        'jp_name':'想星獣姫プリエ',
        'img':'https://i.imgur.com/QbaWuDV.jpg',
        'type':'星獸姬'
      },
      {
        'name':'Star_Beast_Girl_Wood',
        'tc_name':'木星獸姬',
        'jp_name':'轟星獣姫ベルテ',
        'img':'https://i.imgur.com/00UVobJ.jpg',
        'type':'星獸姬'
      },
      {
        'name':'Star_Beast_Girl_Light',
        'tc_name':'光星獸姬',
        'jp_name':'照星獣姫ロゼリ',
        'img':'https://imgur.com/ANXvVIO.jpg',
        'type':'星獸姬'
      },
      {
        'name':'Star_Beast_Girl_Dark',
        'tc_name':'暗星獸姬',
        'jp_name':'幻星獣姫ルゼリッタ',
        'img':'https://i.imgur.com/DZJ33Bk.jpg',
        'type':'星獸姬'
      },
      {
        'name':'Heaven_Demon_Fire',
        'tc_name':'火天魔',
        'jp_name':'紅貌天魔ベスタ',
        'img':'https://i.imgur.com/xAPqeUU.jpg',
        'type':'天魔'
      },
      {
        'name':'Heaven_Demon_Water',
        'tc_name':'水天魔',
        'jp_name':'透映天魔マリア',
        'img':'https://i.imgur.com/wIxhutI.jpg',
        'type':'天魔'
      },
      {
        'name':'Heaven_Demon_Wood',
        'tc_name':'木天魔',
        'jp_name':'再臨天魔エオス',
        'img':'https://i.imgur.com/ZnoZX5C.jpg',
        'type':'天魔'
      },
      {
        'name':'Heaven_Demon_Light',
        'tc_name':'光天魔',
        'jp_name':'双叡天魔ニサ',
        'img':'https://i.imgur.com/IebJE9i.jpg',
        'type':'天魔'
      },
      {
        'name':'Heaven_Demon_Dark',
        'tc_name':'暗天魔',
        'jp_name':'幽命天魔エウノミア',
        'img':'https://i.imgur.com/dzCkg60.jpg',
        'type':'天魔'
      }
  	])
}