export default function handler(req, res) {
  res.status(200).json(
  		{
  			'Number':'3503',
  			'Image':'https://imgur.com/HOqlz4d.jpg',
  			'Name_tc':'火封龍',
  			'Name_jp':'暴焔竜神獣ラルグ',
  			'hp':'19518',
  			'Atk_before':'330x3(4)回',
  			'Atk_after':'369x3(4)回',
  			'Soul':'5格',
  			'Type':['平衡type','砲擊type'],
  			'Characteristic_Before':['飛行','全體化'],
  			'Characteristic_After':['飛行','全體化','貫通LV2&Boss殺手'],
  			'Tp_Transform':'40',
  			'Tp_Characteristic':'技能共嗚柱',
  			'Comment':"火封龍"
  		}
  	)
}